'use client';
import { useEffect, useState } from 'react';
import { confirmPasswordReset, verifyPasswordResetCode } from 'firebase/auth';
import { auth } from '@/lib/firebase/client';

export default function SetupPasswordForm({ code, locale }: { code: string; locale: string }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState('');
  const [state,setState]=useState<'checking'|'ready'|'saving'|'done'|'invalid'>('checking'); const [error,setError]=useState('');
  useEffect(()=>{if(!code){setState('invalid');return;}verifyPasswordResetCode(auth,code).then(e=>{setEmail(e);setState('ready');}).catch(()=>setState('invalid'));},[code]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(password.length<8){setError('كلمة المرور يجب أن تكون 8 أحرف على الأقل');return;}if(password!==confirm){setError('كلمتا المرور غير متطابقتين');return;}setState('saving');try{await confirmPasswordReset(auth,code,password);setState('done');}catch{setError('تعذر حفظ كلمة المرور. قد يكون الرابط منتهي الصلاحية.');setState('ready');}};
  return <main className="setup" dir="rtl"><style>{`*{box-sizing:border-box}.setup{min-height:100vh;display:grid;place-items:center;padding:20px;background:linear-gradient(145deg,#001442,#0d40fc);font-family:'IBM Plex Sans Arabic',Arial}.box{width:min(430px,100%);background:#fff;border-radius:20px;padding:30px;box-shadow:0 25px 80px #00102f88}.logo{font-size:24px;font-weight:900;color:#0d40fc;margin-bottom:22px}.box h1{font-size:23px;color:#001442;margin:0 0 7px}.sub{font-size:13px;color:#718096;margin-bottom:22px}.field{margin-bottom:15px}.field label{display:block;font-size:12px;color:#64748b;margin-bottom:6px}.field input{width:100%;padding:12px;border:1px solid #d7deea;border-radius:10px;font:inherit}.submit{width:100%;border:0;border-radius:10px;padding:13px;background:#0d40fc;color:#fff;font-weight:700;font:inherit;cursor:pointer}.error{background:#fef2f2;color:#dc2626;padding:10px;border-radius:9px;font-size:12px;margin-bottom:14px}.done{background:#ecfdf5;color:#047857;padding:15px;border-radius:12px;line-height:1.8}.link{display:block;text-align:center;margin-top:15px;color:#0d40fc;text-decoration:none;font-size:13px}`}</style><div className="box"><div className="logo">سلوكيرا</div>{state==='checking'&&<p>جاري التحقق من رابط التفعيل...</p>}{state==='invalid'&&<><h1>الرابط غير صالح</h1><p className="sub">الرابط منتهي الصلاحية أو تم استخدامه مسبقًا. اطلب رابطًا جديدًا من الإدارة.</p></>}{state==='done'&&<><h1>تم إعداد حسابك</h1><div className="done">تم حفظ كلمة المرور بنجاح. يمكنك الآن الدخول إلى لوحة المتدرب.</div><a className="link" href={`/${locale}/login`}>الانتقال إلى تسجيل الدخول ←</a></>}{(state==='ready'||state==='saving')&&<><h1>إنشاء كلمة المرور</h1><p className="sub">الحساب: {email}</p><form onSubmit={submit}><div className="field"><label>كلمة المرور الجديدة</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></div><div className="field"><label>تأكيد كلمة المرور</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></div>{error&&<div className="error">{error}</div>}<button className="submit" disabled={state==='saving'}>{state==='saving'?'جاري الحفظ...':'حفظ كلمة المرور'}</button></form></>}</div></main>;
}
