"use client";
import { useState } from "react";

export default function AdminSupervisorOperations({ supervisor, initialSlots, locale }: { supervisor: any; initialSlots: any[]; locale: string }) {
  const [slots, setSlots] = useState(initialSlots);
  const [seats, setSeats] = useState(Number(supervisor.availableSeats || 0));
  const [date, setDate] = useState(""); const [startTime, setStartTime] = useState("09:00"); const [endTime, setEndTime] = useState("12:00");
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const today = new Date().toISOString().slice(0,10);
  const isConsultant = supervisor.accountType === "consultant";
  const refresh = async () => { const data = await fetch(`/api/admin/supervisor-operations?supervisorId=${supervisor.id}`).then((response) => response.json()); setSlots(data.slots || []); };
  const saveSeats = async () => { setLoading(true); const response = await fetch("/api/admin/supervisor-operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"seats",supervisorId:supervisor.id,seats})}); setMessage(response.ok ? "تم تحديث المقاعد" : "تعذر تحديث المقاعد"); setLoading(false); };
  const addSlots = async () => { setLoading(true); const response = await fetch("/api/admin/supervisor-operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"availability",supervisorId:supervisor.id,date,startTime,endTime})}); const data=await response.json(); setMessage(response.ok ? `تمت إضافة ${data.created} موعد` : "تحقق من التاريخ ونطاق الوقت"); if(response.ok){setDate("");await refresh();} setLoading(false); };
  const removeSlot = async (slotId:string) => { const response=await fetch("/api/admin/supervisor-operations",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({slotId,supervisorId:supervisor.id})}); if(response.ok)setSlots((current)=>current.filter((slot)=>slot.id!==slotId)); else setMessage("لا يمكن حذف موعد محجوز"); };
  const grouped=slots.reduce((acc:any,slot:any)=>{(acc[slot.date] ||= []).push(slot);return acc;},{});
  return <div dir="rtl" className={isConsultant ? "consultant-ops" : ""}>
    <style>{`.consultant-ops .ops-grid aside>.ops-card:first-child{display:none}`}</style>
    <style>{`.ops-hero{background:linear-gradient(125deg,#001442,#0D40FC);color:#fff;border-radius:20px;padding:22px 25px;display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:16px}.ops-hero h2{font-size:20px;margin:0 0 5px}.ops-hero p{font-size:12px;color:#cbd8ff;margin:0}.ops-links{display:flex;gap:7px;flex-wrap:wrap}.ops-links a{color:#fff;text-decoration:none;background:#ffffff12;border:1px solid #ffffff25;border-radius:9px;padding:7px 11px;font-size:11px}.ops-grid{display:grid;grid-template-columns:290px 1fr;gap:14px}.ops-card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:17px}.ops-card h3{font-size:14px;margin:0 0 13px}.ops-field{margin-bottom:10px}.ops-field label{display:block;font-size:11px;color:#64748b;margin-bottom:5px}.ops-field input{width:100%;padding:9px;border:1px solid #d1d9e6;border-radius:9px;font:inherit}.ops-times{display:grid;grid-template-columns:1fr 1fr;gap:7px}.ops-btn{width:100%;border:0;border-radius:9px;padding:9px;background:#0d40fc;color:#fff;font:inherit;font-weight:700;cursor:pointer}.seat-row{display:flex;gap:7px}.seat-row input{flex:1;min-width:0;padding:9px;border:1px solid #d1d9e6;border-radius:9px;font:inherit}.seat-row button{border:0;background:#059669;color:#fff;border-radius:9px;padding:9px 13px;font:inherit}.day{border:1px solid #eef2f7;border-radius:12px;padding:12px;margin-bottom:9px}.day-title{font-size:12px;font-weight:700;margin-bottom:8px}.slots{display:flex;flex-wrap:wrap;gap:6px}.slot{font-size:11px;padding:5px 8px;border-radius:99px;background:#ecfdf5;color:#047857;border:1px solid #a7f3d0}.slot.booked{background:#fff7ed;color:#c2410c;border-color:#fed7aa}.slot button{border:0;background:transparent;color:#ef4444;cursor:pointer}.empty{padding:35px;text-align:center;color:#94a3b8;font-size:13px}.ops-msg{margin-top:10px;font-size:12px;color:#0d40fc}@media(max-width:800px){.ops-grid{grid-template-columns:1fr}.ops-hero{align-items:flex-start;flex-direction:column}}`}</style>
    <section className="ops-hero"><div><h2>إدارة {isConsultant ? "مواعيد" : "مواعيد ومقاعد"} {supervisor.name}</h2><p>{supervisor.email} · التغييرات تظهر فورًا في صفحته التعريفية.</p></div><div className="ops-links"><a href={`/${locale}/admin/supervisors`}>← حسابات المشرفين</a><a href={`/${locale}/supervisor/${supervisor.id}`} target="_blank">فتح الصفحة التعريفية ↗</a></div></section>
    <div className="ops-grid"><aside><div className="ops-card" style={{marginBottom:14}}><h3>المقاعد المتاحة</h3><div className="seat-row"><input type="number" min={0} value={seats} onChange={(e)=>setSeats(Math.max(0,Number(e.target.value)))}/><button disabled={loading} onClick={saveSeats}>حفظ</button></div></div><div className="ops-card"><h3>إضافة مواعيد</h3><div className="ops-field"><label>التاريخ</label><input type="date" min={today} value={date} onChange={(e)=>setDate(e.target.value)}/></div><div className="ops-times"><div className="ops-field"><label>من</label><input type="time" value={startTime} onChange={(e)=>setStartTime(e.target.value)}/></div><div className="ops-field"><label>إلى</label><input type="time" value={endTime} onChange={(e)=>setEndTime(e.target.value)}/></div></div><button className="ops-btn" disabled={loading||!date} onClick={addSlots}>إضافة بفواصل 30 دقيقة</button>{message&&<div className="ops-msg">{message}</div>}</div></aside><section className="ops-card"><h3>المواعيد القادمة</h3>{Object.keys(grouped).length===0?<div className="empty">لا توجد مواعيد قادمة</div>:Object.keys(grouped).sort().map((day)=><div className="day" key={day}><div className="day-title">{new Date(day+"T12:00:00").toLocaleDateString("ar-SA",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</div><div className="slots">{grouped[day].sort((a:any,b:any)=>a.time.localeCompare(b.time)).map((slot:any)=><span key={slot.id} className={`slot ${slot.isBooked?"booked":""}`}>{slot.isBooked?"محجوز":"متاح"} · {slot.time} {!slot.isBooked&&<button onClick={()=>removeSlot(slot.id)}>×</button>}</span>)}</div></div>)}</section></div>
  </div>;
}
