"use client";
import { useState } from "react";
import Link from "next/link";

export default function NewTraineeRequests({ trainees, locale }: { trainees:any[]; locale:string }) {
  const [search,setSearch]=useState(""); const [busy,setBusy]=useState("");
  const visible=trainees.filter(t=>[t.name,t.email,t.phone].some(v=>String(v||"").toLowerCase().includes(search.trim().toLowerCase())));
  async function begin(t:any){setBusy(t.id);const response=await fetch("/api/admin/trainee",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({traineeId:t.id,action:"updateLifecycle",stage:"initial_interview",reason:"بدء إجراءات المقابلة الأولية"})});setBusy("");if(response.ok)location.reload();else alert("تعذر نقل الطلب");}
  return <div dir="rtl"><section style={{background:"linear-gradient(125deg,#001442,#0D40FC)",color:"white",padding:24,borderRadius:18,marginBottom:16}}><h2 style={{margin:"0 0 7px",fontSize:21}}>طلبات التسجيل الجديدة</h2><p style={{margin:0,color:"#CBD8FF",fontSize:14,lineHeight:1.8}}>هؤلاء سجلوا حساباتهم من المنصة ولم تبدأ الإدارة معهم أي إجراء بعد. عند بدء الإجراءات ينتقل المتدرب إلى مرحلة المقابلة الأولية.</p></section><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginBottom:16}}><div style={{background:"white",border:"1px solid #E2E8F0",borderTop:"3px solid #0D40FC",borderRadius:14,padding:18}}><b style={{fontSize:28,color:"#0D40FC"}}>{trainees.length}</b><div style={{fontSize:14,color:"#64748B"}}>طلبات جديدة بانتظار المراجعة</div></div><div style={{background:"white",border:"1px solid #E2E8F0",borderTop:"3px solid #059669",borderRadius:14,padding:18}}><b style={{fontSize:28,color:"#059669"}}>{trainees.filter(t=>t.accountStatus==="active").length}</b><div style={{fontSize:14,color:"#64748B"}}>سجلوا حساباتهم بأنفسهم</div></div></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث في الطلبات الجديدة..." style={{width:"100%",padding:12,border:"1px solid #CBD5E1",borderRadius:10,marginBottom:12,fontSize:14}}/><div style={{background:"white",border:"1px solid #E2E8F0",borderRadius:15,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760,fontSize:14}}><thead><tr style={{background:"#F8FAFC"}}>{["المتدرب","الجوال","المؤهل","الرخصة المطلوبة","تاريخ التسجيل","الإجراء"].map(h=><th key={h} style={{padding:14,textAlign:"right",color:"#475569",fontSize:13}}>{h}</th>)}</tr></thead><tbody>{visible.map(t=><tr key={t.id} style={{borderTop:"1px solid #EEF2F7"}}><td style={{padding:14}}><Link href={`/${locale}/admin/trainees/${t.id}`} style={{color:"#001442",fontWeight:800,textDecoration:"none"}}>{t.name}</Link><small style={{display:"block",color:"#94A3B8",fontSize:12}}>{t.email}</small></td><td style={{padding:14}}>{t.phone||"—"}</td><td style={{padding:14}}>{t.qualification||"—"}</td><td style={{padding:14}}>{t.license||"—"}</td><td style={{padding:14}}>{String(t.createdAt||"").slice(0,10)||"—"}</td><td style={{padding:14}}><button disabled={busy===t.id} onClick={()=>void begin(t)} style={{border:0,background:"#0D40FC",color:"white",padding:"9px 14px",borderRadius:9,fontWeight:800,cursor:"pointer"}}>بدء إجراءات المقابلة</button></td></tr>)}</tbody></table>{!visible.length&&<p style={{padding:35,textAlign:"center",color:"#64748B"}}>لا توجد طلبات تسجيل جديدة.</p>}</div></div>;
}
