"use client";
import { useMemo, useState } from "react";

const MONTHS=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
const num=(v:unknown)=>Number(v||0);
const monthOf=(x:any)=>String(x.month||x.date||x.issuedAt||x.createdAt||"").slice(0,7);

export default function SupervisorMonthlyWork({supervisor,trainees,activities,sessions,minutes,documents}:{supervisor:any;trainees:any[];activities:any[];sessions:any[];minutes:any[];documents:any[]}){
  const months=useMemo(()=>Array.from(new Set([...activities,...sessions,...minutes,...documents].map(monthOf).filter(x=>/^\d{4}-\d{2}$/.test(x)))).sort().reverse(),[activities,sessions,minutes,documents]);
  const [selected,setSelected]=useState(months[0]||"");
  const label=(m:string)=>{const [y,i]=m.split("-");return `${MONTHS[Number(i)-1]||i} ${y}`};
  const inMonth=(items:any[])=>items.filter(x=>monthOf(x)===selected);
  const monthActivities=inMonth(activities).filter(x=>x.status==="approved");
  const monthSessions=inMonth(sessions),monthMinutes=inMonth(minutes),monthDocuments=inMonth(documents);
  const individual=monthActivities.filter(x=>String(x.activityType||"").startsWith("supervision_")&&String(x.format||"").toLowerCase()!=="group").reduce((n,x)=>n+num(x.duration),0);
  const group=monthActivities.filter(x=>String(x.activityType||"").startsWith("supervision_")&&String(x.format||"").toLowerCase()==="group").reduce((n,x)=>n+num(x.duration),0);
  const traineeName=(id:string)=>trainees.find(t=>t.id===id)?.name||"—";
  const detailRows=[...monthSessions.map(x=>({...x,kind:"جلسة"})),...monthMinutes.map(x=>({...x,kind:"محضر اجتماع"})),...monthActivities.filter(x=>String(x.activityType||"").startsWith("supervision_")).map(x=>({...x,kind:"ساعات إشراف"})),...monthDocuments.map(x=>({...x,kind:"مستند"}))].sort((a,b)=>String(b.date||b.createdAt||"").localeCompare(String(a.date||a.createdAt||"")));
  return <section dir="rtl" style={{marginBottom:18}}>
    <div style={{background:"linear-gradient(125deg,#001442,#0D40FC)",color:"white",borderRadius:18,padding:"20px 24px",marginBottom:14,display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><small style={{color:"#8FE8FF"}}>سجل المشرف الشهري</small><h2 style={{margin:"5px 0"}}>{supervisor.name}</h2><span style={{color:"#D6E1FF",fontSize:12}}>{supervisor.email}</span></div><a href="#schedule" style={{color:"#001442",background:"white",textDecoration:"none",padding:"9px 13px",borderRadius:9,fontSize:12,fontWeight:700}}>إدارة المواعيد والمقاعد</a></div>
    <div style={{background:"white",border:"1px solid #E2E8F0",borderRadius:16,overflow:"hidden"}}>
      <div style={{padding:"17px 18px 12px"}}><h3 style={{margin:0,color:"#001442"}}>المتابعة حسب الشهر</h3><p style={{fontSize:12,color:"#64748B",margin:"5px 0 0"}}>بنفس تنظيم ملف المشرف: اختر الشهر لمراجعة جميع المتدربين والجلسات المسجلة خلاله.</p></div>
      <div style={{display:"flex",gap:7,overflowX:"auto",padding:"0 18px 13px",borderBottom:"1px solid #E2E8F0"}}>{months.map(m=><button key={m} onClick={()=>setSelected(m)} style={{whiteSpace:"nowrap",border:selected===m?"1px solid #0D40FC":"1px solid #DCE5F0",background:selected===m?"#0D40FC":"#F8FAFC",color:selected===m?"white":"#475569",padding:"9px 14px",borderRadius:9,fontWeight:700,fontFamily:"inherit",cursor:"pointer"}}>{label(m)}</button>)}</div>
      {!selected?<p style={{padding:30,textAlign:"center",color:"#64748B"}}>لا توجد بيانات شهرية مسجلة.</p>:<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:9,padding:16,background:"#F8FAFC"}}>{[["فردي",individual,"#0D40FC"],["جماعي",group,"#7C3AED"],["إجمالي الإشراف",individual+group,"#059669"],["الجلسات",monthSessions.length,"#D97706"],["المحاضر",monthMinutes.length,"#0891B2"]].map(([l,v,c])=><div key={String(l)} style={{background:"white",border:"1px solid #E2E8F0",borderRight:`4px solid ${c}`,borderRadius:11,padding:12}}><b style={{display:"block",fontSize:22,color:String(c)}}>{String(v)}</b><span style={{fontSize:11,color:"#64748B"}}>{String(l)}</span></div>)}</div>
      <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900,fontSize:13}}><thead><tr style={{background:"#EAF0F8"}}>{["المتدرب","الرخصة","الحالة","ساعات العمل","إشراف فردي","إشراف جماعي","مجموع الإشراف","الجلسات","المحاضر","الملف"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{trainees.map(t=>{const a=monthActivities.filter(x=>x.traineeId===t.id);const fw=a.filter(x=>!String(x.activityType||"").startsWith("supervision_")).reduce((n,x)=>n+num(x.duration),0);const ind=a.filter(x=>String(x.activityType||"").startsWith("supervision_")&&String(x.format||"").toLowerCase()!=="group").reduce((n,x)=>n+num(x.duration),0);const grp=a.filter(x=>String(x.activityType||"").startsWith("supervision_")&&String(x.format||"").toLowerCase()==="group").reduce((n,x)=>n+num(x.duration),0);return <tr key={t.id} style={{borderTop:"1px solid #EEF2F7"}}><td style={{...td,fontWeight:800,color:"#001442"}}>{t.name}</td><td style={td}>{t.license||"—"}</td><td style={td}>{t.lifecycleStageLabel||t.status||"مستمر"}</td><td style={td}>{fw}</td><td style={td}>{ind}</td><td style={td}>{grp}</td><td style={{...td,fontWeight:800,color:"#0D40FC"}}>{ind+grp}</td><td style={td}>{monthSessions.filter(x=>x.traineeId===t.id||(x.traineeIds||[]).includes(t.id)).length}</td><td style={td}>{monthMinutes.filter(x=>x.traineeId===t.id||(x.traineeIds||[]).includes(t.id)).length}</td><td style={td}><a href={`/ar/admin/trainees/${t.id}`} style={{color:"#0D40FC",textDecoration:"none",fontWeight:700}}>فتح ←</a></td></tr>})}</tbody></table></div>
      <div style={{padding:18,borderTop:"8px solid #F1F5F9"}}><h3 style={{margin:"0 0 12px",color:"#001442"}}>تفاصيل {label(selected)}</h3><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:720,fontSize:13}}><thead><tr style={{background:"#F8FAFC"}}>{["التاريخ","النوع","المتدرب","المدة/الحالة","التفاصيل"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{detailRows.map((x,i)=><tr key={`${x.kind}-${x.id||i}`} style={{borderTop:"1px solid #EEF2F7"}}><td style={td}>{String(x.date||x.createdAt||"—").slice(0,10)}</td><td style={{...td,fontWeight:700}}>{x.kind}</td><td style={td}>{traineeName(x.traineeId)||(x.traineeIds||[]).map(traineeName).join("، ")}</td><td style={td}>{x.duration?`${x.duration} ساعة`:x.status||x.type||"—"}</td><td style={td}>{x.description||x.discussion||x.title||x.notes||"—"}</td></tr>)}</tbody></table>{!detailRows.length&&<p style={{textAlign:"center",color:"#64748B",padding:20}}>لا توجد تفاصيل مسجلة في هذا الشهر.</p>}</div></div></>}</div>
  </section>;
}
const th:React.CSSProperties={padding:11,textAlign:"right",color:"#475569",fontSize:12,whiteSpace:"nowrap"};
const td:React.CSSProperties={padding:12,color:"#475569",whiteSpace:"nowrap"};
