"use client";
import { useMemo, useState } from "react";

const MONTHS=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
const TYPE:Record<string,string>={direct:"ميداني مباشر",indirect:"ميداني غير مباشر",supervision_direct:"إشراف مباشر",supervision_indirect:"إشراف غير مباشر"};
const STATUS:Record<string,string>={approved:"معتمد",submitted:"بانتظار الاعتماد",draft:"مسودة",revision_requested:"بحاجة لتعديل",rejected:"مرفوض"};
const FORMAT:Record<string,string>={individual:"فردي",group:"جماعي",Individual:"فردي",Group:"جماعي"};
const num=(value:unknown)=>Number(value||0);

export default function TraineeMonthlyHours({activities}:{activities:any[]}){
  const months=useMemo(()=>Array.from(new Set(activities.map(a=>String(a.month||a.date||"").slice(0,7)).filter(Boolean))).sort().reverse(),[activities]);
  const [selected,setSelected]=useState(months[0]||"");
  const rows=activities.filter(a=>String(a.month||a.date||"").slice(0,7)===selected).sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.startTime||"").localeCompare(String(b.startTime||"")));
  const sum=(types:string[])=>rows.filter(a=>types.includes(a.activityType)&&a.status==="approved").reduce((total,a)=>total+num(a.duration),0);
  const direct=sum(["direct"]),indirect=sum(["indirect"]),individual=rows.filter(a=>String(a.activityType).startsWith("supervision_")&&String(a.format).toLowerCase()!=="group"&&a.status==="approved").reduce((n,a)=>n+num(a.duration),0),group=rows.filter(a=>String(a.activityType).startsWith("supervision_")&&String(a.format).toLowerCase()==="group"&&a.status==="approved").reduce((n,a)=>n+num(a.duration),0);
  const supervision=individual+group,fieldwork=direct+indirect;
  const label=(month:string)=>{const [year,index]=month.split("-");return `${MONTHS[Number(index)-1]||index} ${year}`};
  const cards=[["إجمالي الخبرة الميدانية",fieldwork,"#0D40FC"],["ميداني مباشر",direct,"#059669"],["ميداني غير مباشر",indirect,"#0891B2"],["إجمالي الإشراف",supervision,"#7C3AED"],["إشراف فردي",individual,"#D97706"],["إشراف جماعي",group,"#C2410C"]];
  return <section dir="rtl" style={{background:"white",border:"1px solid #DCE5F0",borderRadius:18,overflow:"hidden"}}>
    <header style={{padding:"20px 22px 15px",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h3 style={{margin:0,color:"#001442",fontSize:19}}>سجل الساعات الشهري</h3><p style={{margin:"5px 0 0",color:"#64748B",fontSize:13}}>عرض مطابق لطريقة ملف التتبع: ملخص الشهر ثم تفاصيل كل نشاط.</p></div><div style={{fontSize:13,color:"#475569",background:"#F8FAFC",padding:"8px 12px",borderRadius:9}}>إجمالي السجلات: <b>{activities.length}</b></div></header>
    <div style={{display:"flex",gap:7,overflowX:"auto",padding:"0 20px 14px",borderBottom:"1px solid #E2E8F0"}}>{months.map(month=><button key={month} onClick={()=>setSelected(month)} style={{whiteSpace:"nowrap",border:selected===month?"1px solid #0D40FC":"1px solid #DCE5F0",background:selected===month?"#0D40FC":"#F8FAFC",color:selected===month?"white":"#475569",padding:"9px 15px",borderRadius:"10px 10px 3px 3px",fontWeight:800,fontFamily:"inherit",cursor:"pointer"}}>{label(month)}<small style={{display:"block",fontWeight:500,opacity:.8,marginTop:2}}>{activities.filter(a=>String(a.month||a.date||"").slice(0,7)===month).length} سجل</small></button>)}</div>
    {selected?<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9,padding:18,background:"#F8FAFC"}}>{cards.map(([name,value,color])=><div key={String(name)} style={{background:"white",border:"1px solid #E2E8F0",borderRight:`4px solid ${color}`,borderRadius:11,padding:13}}><b style={{display:"block",fontSize:22,color:String(color)}}>{num(value).toFixed(1).replace(".0","")}</b><span style={{fontSize:12,color:"#64748B"}}>{String(name)}</span></div>)}</div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1150,fontSize:13}}><thead><tr style={{background:"#EAF0F8",color:"#334155"}}>{["#","التاريخ","من","إلى","نوع النشاط","التصنيف","نمط الإشراف","المدة","الحالة","وصف النشاط"].map(h=><th key={h} style={{padding:"11px 10px",textAlign:"right",border:"1px solid #D7E0EB",fontSize:12,fontWeight:800}}>{h}</th>)}</tr></thead><tbody>{rows.map((a,index)=><tr key={a.id} style={{background:index%2?"#FAFCFF":"white"}}><td style={td}>{index+1}</td><td style={td}>{a.date||"—"}</td><td style={td}>{a.startTime||"—"}</td><td style={td}>{a.endTime||"—"}</td><td style={{...td,fontWeight:700,color:String(a.activityType).startsWith("supervision_")?"#7C3AED":"#0D40FC"}}>{TYPE[a.activityType]||a.activityType}</td><td style={td}>{a.category||a.setting||"—"}</td><td style={td}>{FORMAT[a.format]||a.format||"—"}</td><td style={{...td,fontWeight:800}}>{num(a.duration)}</td><td style={td}><span style={{padding:"4px 8px",borderRadius:99,background:a.status==="approved"?"#ECFDF5":"#FFF7ED",color:a.status==="approved"?"#047857":"#C2410C",fontSize:11,fontWeight:700}}>{STATUS[a.status]||a.status}</span></td><td style={{...td,minWidth:280,whiteSpace:"normal",lineHeight:1.6}}>{a.description||"—"}</td></tr>)}</tbody><tfoot><tr style={{background:"#001442",color:"white",fontWeight:800}}><td colSpan={7} style={{padding:12}}>إجمالي الساعات المسجلة خلال {label(selected)}</td><td style={{padding:12}}>{rows.reduce((n,a)=>n+num(a.duration),0)}</td><td colSpan={2} style={{padding:12}}>المعتمد: {fieldwork+supervision} ساعة</td></tr></tfoot></table></div></>:<div style={{padding:40,textAlign:"center",color:"#64748B"}}>لا توجد ساعات مسجلة.</div>}
  </section>;
}

const td:React.CSSProperties={padding:"10px",border:"1px solid #E2E8F0",verticalAlign:"top",whiteSpace:"nowrap"};
